export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_RECIPES = "GET_RECIPES";
export const GET_SPECIFIC_RECIPE = "GET_SPECIFIC_RECIPE";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const GET_BULK_RECIPE_INFO = "GET_BULK_RECIPE_INFO";
export const RECIPES_ERROR = "RECIPES_ERROR";
export const SAVE_RECIPE = "SAVE_RECIPE";
export const REMOVE_SAVED_RECIPE = "REMOVE_SAVED_RECIPE";
export const SEARCH_RECIPES = "SEARCH_RECIPES";

export const CLEAR_RECIPES = "CLEAR_RECIPES";

export const SET_LOADING = "SET_LOADING";
